// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljtodfwuofhwihcmvewd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqdG9kZnd1b2Zod2loY212ZXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTU0MDMsImV4cCI6MjA2NzI3MTQwM30.tJoLrKPbfL7X_ndP4nIzzvvWAYt4PHzjDuOuDcu2yfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});